_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 49
                - 51
                - 55
                - 95
                - 105
            "2":
                - 49
                - 51
                - 55
                - 95
                - 105
            "3":
                - 2
                - 23
                - 55
                - 62
            "4": 3.12.7
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": darwin-arm64
num_validation_samples:
    value: 87
