_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 49
                - 51
                - 55
                - 95
                - 105
            "2":
                - 49
                - 51
                - 55
                - 95
                - 105
            "3":
                - 2
                - 23
                - 55
                - 58
                - 61
                - 62
            "4": 3.12.7
            "5": 0.18.5
            "8":
                - 1
                - 5
            "10":
                - 11
            "12": 0.18.5
            "13": darwin-arm64
created_at:
    value: "2024-10-19 01:25:03"
error:
    value:
        code: null
        message: null
        param: null
estimated_finish:
    value: null
fine_tuned_model:
    value: ft:gpt-3.5-turbo-0125:personal::AJiJ8bR6
finished_at:
    value: "2024-10-19 01:31:52"
hyperparameters:
    value:
        batch_size: 1
        learning_rate_multiplier: 2
        n_epochs: 3
id:
    value: ftjob-Ef468OMa5MKacvqzD0LYtGEV
integrations:
    value: []
model:
    value: gpt-3.5-turbo-0125
n_train:
    value: 30
n_valid:
    value: 87
object:
    value: fine_tuning.job
organization_id:
    value: org-v1K2Lxyjnu8PFhpx9OPExASg
result_files:
    value: file-RH2WFPkKmYye7mYt99YYKR6I
seed:
    value: 486798962
status:
    value: succeeded
trained_tokens:
    value: 11415
training_file:
    value: file-VYndPZHIuBw6XHOg6LRAUPG2
user_provided_suffix:
    value: null
validation_file:
    value: file-OPwQ1OtKgw2qOL5byaYdcuQE
